# Generated by Django 4.2.17 on 2024-12-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palmares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_section', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='eleves',
            old_name='pre_nom',
            new_name='prenom',
        ),
        migrations.CreateModel(
            name='Resultats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palmares.anneescolaires')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palmares.classes')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palmares.eleves')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palmares.sections')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palmares.sections'),
        ),
    ]
