# Generated by Django 4.2.17 on 2025-01-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palmares', '0002_anneescolaires_classes_sections_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANNEE_SCOLAIRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=9, unique=True, verbose_name='Année scolaire')),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
                'db_table': 'table_annee_scolaire',
            },
        ),
        migrations.CreateModel(
            name='CLASSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=50, verbose_name='Nom de la classe')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='palmares.annee_scolaire', verbose_name='Année scolaire')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'db_table': 'table_classe',
            },
        ),
        migrations.CreateModel(
            name='ELEVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('post_nom', models.CharField(max_length=30, verbose_name='Post-nom')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prénom')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'db_table': 'table_eleve',
            },
        ),
        migrations.CreateModel(
            name='RESULTAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Pourcentage')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='palmares.annee_scolaire', verbose_name='Année scolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='palmares.classe', verbose_name='Classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='palmares.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Résultat',
                'verbose_name_plural': 'Résultats',
                'db_table': 'table_resultat',
            },
        ),
        migrations.CreateModel(
            name='SECTION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_section', models.CharField(max_length=50, verbose_name='Nom de la section')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='palmares.annee_scolaire', verbose_name='Année scolaire')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'table_section',
            },
        ),
        migrations.RemoveField(
            model_name='classes',
            name='section',
        ),
        migrations.RemoveField(
            model_name='resultats',
            name='annee_scolaire',
        ),
        migrations.RemoveField(
            model_name='resultats',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='resultats',
            name='eleve',
        ),
        migrations.RemoveField(
            model_name='resultats',
            name='section',
        ),
        migrations.DeleteModel(
            name='AnneeScolaires',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Eleves',
        ),
        migrations.DeleteModel(
            name='Resultats',
        ),
        migrations.DeleteModel(
            name='Sections',
        ),
        migrations.AddField(
            model_name='resultat',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='palmares.section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='classe',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='palmares.section', verbose_name='Section'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('nom_section', 'annee_scolaire'), name='unique_section_annee'),
        ),
        migrations.AddConstraint(
            model_name='resultat',
            constraint=models.UniqueConstraint(fields=('eleve', 'classe', 'section', 'annee_scolaire'), name='unique_resultat'),
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(fields=('nom_classe', 'section', 'annee_scolaire'), name='unique_classe_section_annee'),
        ),
    ]
