# Generated by Django 4.2.17 on 2025-01-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palmares', '0004_remove_classe_unique_classe_section_annee_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classe',
            name='unique_classe_section_annee',
        ),
        migrations.AddConstraint(
            model_name='classe',
            constraint=models.UniqueConstraint(fields=('nom_classe',), name='unique_classe'),
        ),
    ]
